import {
  MuscleGroup,
  ExerciseCategory,
  EquipmentType,
  type PrismaClient,
} from '@/prisma/generated/client';

// ============================================================
// 100XU Athletic Performance System catalog
// ============================================================
// Seeded per user: at registration (so a new account is not empty) and by the
// demo seed. Every entry is a movement from the 100-day century blueprint:
// name, prescribed load and the technical execution cue. Generic lift names
// use the full equipment word so the name always matches its equipment type.

export interface CatalogExercise {
  name: string;
  muscleGroup: MuscleGroup;
  category: ExerciseCategory;
  equipmentType: EquipmentType;
  defaultRestSec: number;
  usesBodyweight?: boolean;
  notes?: string;
}

export const EXERCISE_CATALOG: CatalogExercise[] = [
  // Dumbbell work (Block 01 to 10)
  {
    name: 'Dual dumbbell front squats',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Heads of DBs resting on delts, elbows parallel to deck, descend past parallel. Load: Dual 10-15 kg DBs.',
  },
  {
    name: 'Forward alternating dumbbell lunges',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Suitcase carry, vertical shin on lead leg, light floor tap with rear knee. Load: Dual 10-12.5 kg DBs.',
  },
  {
    name: 'Dual dumbbell thrusters',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Deep front squat; erupt through heels and punch DBs overhead in one movement. Load: Dual 10-15 kg DBs.',
  },
  {
    name: 'Dumbbell renegade rows',
    muscleGroup: MuscleGroup.BACK_THICKNESS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Push-up plank; pull dumbbell to ribcage without allowing hips to tilt. Load: Dual 10-15 kg DBs.',
  },
  {
    name: 'Front-rack walking dumbbell lunges',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'DBs resting on shoulders; continuous forward strides with soft knee touch. Load: Dual 10-12.5 kg DBs.',
  },
  {
    name: 'Alternating dumbbell snatch',
    muscleGroup: MuscleGroup.SHOULDERS_LATERAL,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Pull straight off floor, jump through hips, punch DB overhead in one motion. Load: 12.5-17.5 kg DB.',
  },
  {
    name: 'Dumbbell push press',
    muscleGroup: MuscleGroup.SHOULDERS_FRONT,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Quick 2-inch vertical dip, violent hip extension, drive dumbbells to lockout. Load: Dual 12.5-17.5 kg DBs.',
  },
  {
    name: 'Weighted dumbbell box step-ups',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Step completely onto box; drive through lead heel without jumping off rear foot. Load: Dual 8-12 kg DBs + Box.',
  },
  {
    name: 'Dumbbell devil press',
    muscleGroup: MuscleGroup.TRICEPS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 120,
    notes: 'Burpee with chest onto DB handles; swing and snatch DBs overhead in one stroke. Load: Dual 10-15 kg DBs.',
  },
  {
    name: 'Dumbbell hang clean and squat',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Hang pull to front rack into instantaneous deep squat below knee crease. Load: Dual 10-15 kg DBs.',
  },
  {
    name: 'Dumbbell floor press with bridge hold',
    muscleGroup: MuscleGroup.CHEST,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Hold hips up in glute bridge while pressing dumbbells up to complete lockout. Load: Dual 12.5-17.5 kg DBs.',
  },
  {
    name: 'Dumbbell Romanian deadlifts',
    muscleGroup: MuscleGroup.LOWER_BACK,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 120,
    notes: 'Hips back, flat back, slide DBs down shins until hamstrings stretch, snap erect. Load: Dual 15-20 kg DBs.',
  },
  {
    name: 'Single-leg dumbbell Romanian deadlift',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Hinge on single foot, rear leg straight, lower DB to midshin, drive glute. Load: 12-16 kg DB.',
  },
  {
    name: 'Dumbbell Bulgarian split squats',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Rear foot on box; lower until front thigh is parallel to deck; drive heel. Load: Dual 10-15 kg DBs.',
  },
  {
    name: 'Single-arm dumbbell push press',
    muscleGroup: MuscleGroup.SHOULDERS_FRONT,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Quick dip and violent single-arm drive to lock DB directly overhead. Load: 12.5-17.5 kg DB.',
  },
  {
    name: 'Dual dumbbell clean and thruster cluster',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 120,
    notes: 'DBs tap deck, clean to rack, full front squat, explosive overhead press. Load: Dual 10-15 kg DBs.',
  },
  {
    name: 'Alternating dumbbell hang snatches',
    muscleGroup: MuscleGroup.SHOULDERS_LATERAL,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Hinge hips, pull DB straight overhead in one violent, continuous stroke. Load: 12.5-17.5 kg DB.',
  },
  {
    name: 'Dumbbell push-up to snatch',
    muscleGroup: MuscleGroup.CHEST,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'One hand on DB push-up; immediately pull and snatch DB overhead. Load: Single 12.5-15 kg DB.',
  },
  {
    name: 'Speed dual dumbbell thrusters',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Continuous piston tempo; zero hesitation at bottom or top of press. Load: Dual 10-12.5 kg DBs.',
  },
  {
    name: 'Heavy dual dumbbell thrusters',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 120,
    notes: 'Full front squat depth into explosive locked overhead press. Load: Dual 12.5-17.5 kg DBs.',
  },
  {
    name: 'Dual dumbbell walking lunges',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Suitcase hold; deep lunge steps with knee tap, driving forward continuously. Load: Dual 12.5-15 kg DBs.',
  },
  {
    name: 'Ski-pull simulator dumbbell hinge drives',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Elevate on toes, aggressive hip hinge, drive dumbbells downward past hips. Load: Dual 8-12 kg DBs.',
  },
  {
    name: 'Rowing simulator sumo squat rows',
    muscleGroup: MuscleGroup.BACK_WIDTH,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Deep squat drive, explosive hip extension into simultaneous upper pull. Load: Dual 12.5-15 kg DBs.',
  },
  {
    name: 'Wall-sit dumbbell bicep curls',
    muscleGroup: MuscleGroup.BICEPS,
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 75,
    notes: 'Thighs pinned at 90 deg against wall; execute strict curls while quads burn. Load: Dual 8-10 kg DBs.',
  },
  {
    name: 'Overhead dumbbell walking lunges',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Arms rigidly locked overhead; forward lunges challenging shoulder stability. Load: Single/Dual 10-12.5 kg DB.',
  },
  {
    name: 'Burpee jump over dumbbell',
    muscleGroup: MuscleGroup.CHEST,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Chest hits deck, snap feet in, two-foot lateral jump over dumbbell. Load: Single DB.',
  },
  {
    name: 'Hollow body dumbbell pullover',
    muscleGroup: MuscleGroup.ABS,
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 75,
    notes: 'Lock lower spine down; reach DB overhead with straight arms and return to chest. Load: Single 10-12.5 kg DB.',
  },
  {
    name: 'Side plank dumbbell rotations',
    muscleGroup: MuscleGroup.ABS,
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 75,
    notes: 'High side plank; thread DB beneath torso then extend straight toward ceiling. Load: 4-6 kg DB.',
  },
  {
    name: 'Dumbbell renegade row to push-up',
    muscleGroup: MuscleGroup.BACK_THICKNESS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Row Left + Row Right + strict Push-Up on DBs = 1 complete repetition. Load: Dual 10-15 kg DBs.',
  },
  {
    name: 'Wall-ball simulator thrusters',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Squat below parallel and use hip velocity to launch DBs straight overhead. Load: Dual 8-12 kg DBs.',
  },
  {
    name: 'Spiderman push-ups on dumbbells',
    muscleGroup: MuscleGroup.CHEST,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Hands on dumbbells; bring lateral knee to touch DB handle at bottom of press. Load: Dual Hex DBs.',
  },
  {
    name: 'Deficit push-ups on hex dumbbells',
    muscleGroup: MuscleGroup.TRICEPS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Hands on handles; lower chest deeply between dumbbells for maximal stretch. Load: Dual Hex DBs.',
  },

  // Kettlebell work (Block 01 to 10)
  {
    name: 'Russian kettlebell swings',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Aggressive hip snap to eye line; locked knees and tight glute squeeze at apex. Load: 16-24 kg KB.',
  },
  {
    name: 'Heavy kettlebell carry paces',
    muscleGroup: MuscleGroup.FOREARMS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Pack shoulders down and back, tight grip, 10 deliberate heel-to-toe paces. Load: Dual 16-24 kg KBs.',
  },
  {
    name: 'Kettlebell goblet sumo deadlifts',
    muscleGroup: MuscleGroup.GLUTES,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Wide stance, hinge deeply at hips, push the floor away through the heels. Load: 20-28 kg KB.',
  },
  {
    name: 'American kettlebell swings',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Hip snap propels KB directly overhead to 12 o clock; core locked to protect back. Load: 16-20 kg KB.',
  },
  {
    name: 'Kettlebell goblet squats with pause',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Hold horn at collarbone; 2s freeze at parallel; explode to standing lockout. Load: 16-24 kg KB.',
  },
  {
    name: 'Overhead kettlebell carry paces',
    muscleGroup: MuscleGroup.FOREARMS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Arm locked vertical beside ear, ribs clamped down, 10 steady strides. Load: 12-16 kg KB.',
  },
  {
    name: 'Single-arm kettlebell swings',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Anti-rotational swing; keep shoulders square to front wall throughout. Load: 16-20 kg KB.',
  },
  {
    name: 'Kettlebell deadlift to high pull',
    muscleGroup: MuscleGroup.BACK_WIDTH,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Deadlift from floor, explode at hips, pull elbows high and wide to chin level. Load: 16-24 kg KB.',
  },
  {
    name: 'Kettlebell clean and push press',
    muscleGroup: MuscleGroup.SHOULDERS_FRONT,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Smooth clean into rack, shallow dip, drive weight straight overhead. Load: 16-20 kg KB.',
  },
  {
    name: 'Kettlebell goblet reverse lunges',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'KB held at chin; step back into deep 90 deg lunge; drive up through front heel. Load: 16-24 kg KB.',
  },
  {
    name: 'Kettlebell Russian twists',
    muscleGroup: MuscleGroup.ABS,
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 75,
    notes: 'V-sit hold with heels floating; tap kettlebell to floor on alternating flanks. Load: 8-12 kg KB.',
  },
  {
    name: 'Kettlebell halo to squat',
    muscleGroup: MuscleGroup.SHOULDERS_REAR,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Circle KB around head, catch at chest, sink into deep squat; alternate halo direction. Load: 12-16 kg KB.',
  },
  {
    name: 'Heavy kettlebell farmer walk',
    muscleGroup: MuscleGroup.FOREARMS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 120,
    notes: 'Crush handles, chest high, walk with zero lateral torso swaying. Load: Dual 20-28 kg KBs.',
  },
  {
    name: 'Alternating hand kettlebell swings',
    muscleGroup: MuscleGroup.GLUTES,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Switch hands smoothly at the apex float with crisp hip extension. Load: 16-20 kg KB.',
  },
  {
    name: 'Kettlebell gorilla rows',
    muscleGroup: MuscleGroup.BACK_THICKNESS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Deep deadlift hinge; row one bell up while pressing the other down into deck. Load: Dual 16-20 kg KBs.',
  },
  {
    name: 'Kettlebell clean to squat',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Swing clean to rack, instantly drop into deep front squat, explode up. Load: 16-20 kg KB.',
  },
  {
    name: 'Double kettlebell swings',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 120,
    notes: 'Bells outside knees; violent synchronized hip hinge and drive to chest line. Load: Dual 16-20 kg KBs.',
  },
  {
    name: 'Heavy kettlebell goblet thrusters',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 120,
    notes: 'Hold heavy bell at chest; sink to the hole; drive and punch overhead. Load: 20-24 kg KB.',
  },
  {
    name: 'Heavy farmer carry turnover',
    muscleGroup: MuscleGroup.FOREARMS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 120,
    notes: 'Maximum grip test; quick compact strides with locked thoracic extension. Load: Dual 24-32 kg KBs.',
  },
  {
    name: 'Burpee to kettlebell deadlift',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Burpee between bells; snap into hip hinge and stand tall with weights. Load: Dual 16-24 kg KBs.',
  },
  {
    name: 'Kettlebell swing to goblet squat',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Russian swing, catch horn at chest, sink into deep squat, repeat. Load: 16-20 kg KB.',
  },
  {
    name: 'Sled pull simulator bent kettlebell rows',
    muscleGroup: MuscleGroup.BACK_WIDTH,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Hinged flat back; row heavy bell to navel simulating hand-over-hand rope pull. Load: 24-32 kg KB.',
  },
  {
    name: 'Rapid touch and go kettlebell swings',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Crisp hip pop, aggressive spike down, instant reversal off hamstrings. Load: 16-20 kg KB.',
  },
  {
    name: 'American kettlebell overhead swings',
    muscleGroup: MuscleGroup.SHOULDERS_LATERAL,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Full overhead vertical lock; hips drive bell upward in single continuous line. Load: 16-20 kg KB.',
  },
  {
    name: 'Single-arm kettlebell thrusters',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Rack on one shoulder, deep squat, punch overhead with core braced against lean. Load: 12-16 kg KB.',
  },
  {
    name: 'Kettlebell clean, squat and press',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 120,
    notes: 'Swing clean to rack, front squat, stand and press overhead. Flawless flow. Load: 16-20 kg KB.',
  },
  {
    name: 'Sumo deadlift high pulls',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Violent triple extension; elbows punch high above shoulders. Load: 20-24 kg KB.',
  },
  {
    name: 'Suitcase walking lunges',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Kettlebells held at sides; continuous walking forward lunges with soft knee touch. Load: Dual 12-16 kg KBs.',
  },
  {
    name: 'Asymmetric farmer carry',
    muscleGroup: MuscleGroup.FOREARMS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Uneven loading forces contralateral obliques to fire continuously during walk. Load: Heavy KB + DB.',
  },
  {
    name: 'Farmer high-knee march',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 75,
    notes: 'Farmer grip hold; lift lead thigh to parallel on every steady stride. Load: Dual 16-24 kg KBs.',
  },
  {
    name: 'Unilateral suitcase carry paces',
    muscleGroup: MuscleGroup.FOREARMS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 90,
    notes: 'Single-sided load; contract opposite obliques to keep shoulders totally level. Load: 20-24 kg KB single.',
  },
  {
    name: 'Heavy kettlebell farmer carry strides',
    muscleGroup: MuscleGroup.FOREARMS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 120,
    notes: 'Iron grip, locked lats; 10 heavy, controlled, rapid paces per round. Load: Dual 20-28 kg KBs.',
  },

  // Bodyweight work (Block 01 to 10)
  {
    name: 'Strict hand-release push-ups',
    muscleGroup: MuscleGroup.CHEST,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'Chest flat to floor, lift palms momentarily, press up without sagging hips. Load: Bodyweight.',
  },
  {
    name: 'Piston mountain climbers',
    muscleGroup: MuscleGroup.ABS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'High tempo knee drives to chest; keep hips lower than shoulder line. Load: Bodyweight.',
  },
  {
    name: 'Full chest-to-deck burpees',
    muscleGroup: MuscleGroup.CHEST,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Chest and thighs touch deck, snap feet forward wide, vertical jump with clap. Load: Bodyweight.',
  },
  {
    name: 'Plyo box jumps with step down',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Two-foot explosive takeoff, quiet athletic landing, step down to reset. Load: 20-24 inch Box.',
  },
  {
    name: 'Box step-overs facing box',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'Step up onto box center, pivot, and step down facing opposite side smoothly. Load: 20-24 inch Box.',
  },
  {
    name: 'Plyo box high jumps',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Vertical explosion, land softly, stand to complete hip lockout at top. Load: 24 inch Box.',
  },
  {
    name: 'Box lateral step-ups with high knee',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Stand beside box, step up laterally, drive opposite knee to chest level. Load: 20-24 inch Box.',
  },
  {
    name: 'Speed farmer carry strides',
    muscleGroup: MuscleGroup.FOREARMS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 120,
    notes: 'Fast-turnover sprint strides carrying bells with rigid shoulder control. Load: Dual 16-20 kg KBs.',
  },
  {
    name: 'Box step-overs with dual dumbbells',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Hold dumbbells at sides; travel over box top with steady rapid cadence. Load: Dual 8-10 kg DBs + Box.',
  },
  {
    name: 'Heavy Russian kettlebell swings',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.KETTLEBELL,
    defaultRestSec: 120,
    notes: 'Brace core, hinge back deep, fire glutes with maximum power to eye height. Load: 24-32 kg KB.',
  },
  {
    name: 'Box step-overs with overhead dumbbell',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.DUMBBELL,
    defaultRestSec: 90,
    notes: 'Punch single DB overhead; step onto and over box without dropping elbow. Load: Single 10-15 kg DB + Box.',
  },
  {
    name: 'Burpee broad jumps',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Chest to floor, snap up to feet, immediate explosive 2-foot forward bound. Load: Bodyweight.',
  },
  {
    name: 'Box jump-overs',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Jump up onto box top, hop down the far side, immediate pivot to repeat. Load: 20-24 inch Box.',
  },
  {
    name: 'Plank up-downs',
    muscleGroup: MuscleGroup.ABS,
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 60,
    usesBodyweight: true,
    notes: 'Alternate lead arm each rep; squeeze glutes to keep pelvis totally stationary. Load: Bodyweight.',
  },
  {
    name: 'Box rebound jumps',
    muscleGroup: MuscleGroup.CALVES,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'Land softly on box, step down, instantly spring off forefoot back onto box. Load: 20-24 inch Box.',
  },
  {
    name: 'Lateral box step-overs',
    muscleGroup: MuscleGroup.GLUTES,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'Travel sideways over box; plant lead foot, stand tall, step down other side. Load: 20 inch Box.',
  },
  {
    name: 'Athletic burpee broad jumps',
    muscleGroup: MuscleGroup.HAMSTRINGS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Full chest-to-deck burpee followed by an explosive forward broad jump. Load: Bodyweight.',
  },
  {
    name: 'Wall sled drive marches',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'Hands on wall at 45 deg angle, drive alternating knees hard against resistance. Load: Isometric Wall Load.',
  },
  {
    name: 'Quad bear crawls',
    muscleGroup: MuscleGroup.SHOULDERS_FRONT,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'Knees hovering 1 inch off floor; forward crawl maintaining low 45 deg torso angle. Load: Bodyweight.',
  },
  {
    name: 'High box jumps with step down',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Maximum vertical hip drive; land softly in quarter squat; step down to reset. Load: 24-30 inch Box.',
  },
  {
    name: 'Box jumps to stand tall',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Land softly on top of box, stand to full vertical hip lockout before stepping down. Load: 24 inch Box.',
  },
  {
    name: 'Plyo box jumps with soft stick',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Absorb landing silently; stand tall to full vertical hip extension. Load: 24 inch Box.',
  },
  {
    name: 'Alternating jump lunges',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'Fast switch in mid-air, touch rear knee, explode back up instantly. Load: Bodyweight.',
  },
  {
    name: 'High knees to sprawl drop',
    muscleGroup: MuscleGroup.ABS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: '4 high knees + 1 chest drop sprawl = 1 rep; complete 10 reps to finish round. Load: Bodyweight.',
  },
  {
    name: 'Navy SEAL 3-pump burpees',
    muscleGroup: MuscleGroup.CHEST,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Drop down, 3 push-ups + 2 knee-to-elbow drives inside each push-up, jump. Load: Bodyweight.',
  },
  {
    name: 'Box depth drop to vertical pop',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 75,
    usesBodyweight: true,
    notes: 'Step off box, hit floor, instantaneously redirect kinetic energy straight up. Load: 20 inch Box.',
  },
  {
    name: 'Box lateral shuffle taps',
    muscleGroup: MuscleGroup.CALVES,
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 60,
    usesBodyweight: true,
    notes: 'Lateral shuffle tap top of box, drop to side, immediate athletic rebound. Load: 20 inch Box.',
  },
  {
    name: 'Box rapid toe-taps',
    muscleGroup: MuscleGroup.CALVES,
    category: ExerciseCategory.ISOLATION,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 60,
    usesBodyweight: true,
    notes: 'High cadence turnover; spring off balls of feet, alternate tapping box top. Load: 20 inch Box.',
  },
  {
    name: 'Burpee box step-overs',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Burpee facing box, jump up, step across top of box to opposite floor. Load: 20-24 inch Box.',
  },
  {
    name: 'Burpee box-over jumps',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BODYWEIGHT,
    defaultRestSec: 90,
    usesBodyweight: true,
    notes: 'Chest-to-deck burpee, spring over box top to far side without standing upright. Load: 20-24 inch Box.',
  },

  // Foundation barbell staple: the catalog gate requires at least five
  // distinct equipment types, and the blueprint only spans four.
  {
    name: 'Barbell back squat',
    muscleGroup: MuscleGroup.QUADS,
    category: ExerciseCategory.COMPOUND,
    equipmentType: EquipmentType.BARBELL,
    defaultRestSec: 150,
    notes: 'Bar across the upper back, brace hard, descend past parallel, drive through the whole foot.',
  },

  // ============================================================
  // Duration/distance based: sets on these log a time (and optionally a
  // distance) instead of weight x reps. Grouped under OTHER - cardio does
  // not map to a single muscle group.
  {
    name: 'Running',
    muscleGroup: MuscleGroup.OTHER,
    category: ExerciseCategory.CARDIO,
    equipmentType: EquipmentType.CARDIO,
    defaultRestSec: 60,
    notes: 'Steady pace you could hold a conversation at, or intervals. Log the time and distance.',
  },
  {
    name: 'Rowing machine',
    muscleGroup: MuscleGroup.OTHER,
    category: ExerciseCategory.CARDIO,
    equipmentType: EquipmentType.CARDIO,
    defaultRestSec: 60,
    notes: 'Drive with the legs, then swing the hips, then pull. Log the time and distance.',
  },
  {
    name: 'Cycling',
    muscleGroup: MuscleGroup.OTHER,
    category: ExerciseCategory.CARDIO,
    equipmentType: EquipmentType.CARDIO,
    defaultRestSec: 60,
    notes: 'Outdoor or stationary bike. Log the time and distance.',
  },
  {
    name: 'Jump rope',
    muscleGroup: MuscleGroup.OTHER,
    category: ExerciseCategory.CARDIO,
    equipmentType: EquipmentType.CARDIO,
    defaultRestSec: 60,
    notes: 'Light on the feet, elbows close, turn from the wrists. Log the time.',
  },
];

// Upserts the default catalog for a user. Returns a name -> exercise id map so
// callers can wire up a starter program. Idempotent (safe to re-run).
// Pass onlyNames to seed a subset (registration seeds free basics only;
// challenge-only movements stay out of pickers and custom programs).
// Fast path: brand-new accounts get one createMany instead of N upserts -
// registration used to take 10s+ over remote Postgres.
export async function seedExerciseCatalog(
  prisma: PrismaClient,
  userId: string,
  onlyNames?: Set<string>,
): Promise<Map<string, string>> {
  const map = new Map<string, string>();
  const list = onlyNames ? EXERCISE_CATALOG.filter((e) => onlyNames.has(e.name)) : EXERCISE_CATALOG;
  if ((await prisma.exercise.count({ where: { userId } })) === 0 && list.length > 0) {
    await prisma.exercise.createMany({
      data: list.map((data) => ({ ...data, userId })),
      skipDuplicates: true,
    });
    const rows = await prisma.exercise.findMany({
      where: { userId },
      select: { id: true, name: true },
    });
    for (const row of rows) map.set(row.name, row.id);
    return map;
  }
  for (const data of list) {
    const exercise = await prisma.exercise.upsert({
      where: { userId_name: { userId, name: data.name } },
      update: data,
      create: { ...data, userId },
    });
    map.set(data.name, exercise.id);
  }
  return map;
}
